### ISSUE TITLE
createImageEdit request example fails with content null

### ISSUE THREAD

**Issue by ajavamind** [TheoKanning/openai-java#197]
I modified the example to perform a Image edit where an input file is used.
Using windows 11 and oracle JDK 17
This issue may be same as #118

Here is the modified example code and run gradlew results:

package example;

import com.theokanning.openai.service.OpenAiService;
import com.theokanning.openai.completion.CompletionRequest;
import com.theokanning.openai.image.CreateImageRequest;
import com.theokanning.openai.image.CreateImageVariationRequest;
import com.theokanning.openai.image.CreateImageEditRequest;
import java.io.File;

class OpenAiApiExample {
    public static void main(String... args) {
        String token = System.getenv("OPENAI_TOKEN");
        OpenAiService service = new OpenAiService(token);

//        System.out.println("\nCreating completion...");
//        CompletionRequest completionRequest = CompletionRequest.builder()
////                .model("ada")
//                .model("gpt-3.5-turbo")
//                .prompt("code java method to compute pi to 20 digits")
//                .echo(true)
//                .user("testing")
//                .n(3)
//                .build();
//        service.createCompletion(completionRequest).getChoices().forEach(System.out::println);

        System.out.println("\nCreating Image...");
//        CreateImageVariationRequest request = CreateImageVariationRequest.builder()
//                //.prompt("Two tabby cats breakdancing")
//				.n(2)
//                .build();
        CreateImageEditRequest request = CreateImageEditRequest.builder()
                .prompt("change colors to red")
				.n(2)
                .build();
        String imagePath = File.separator+"images"+File.separator+"dog_breakdancing_with_cat.png";
		File imageFile = new File(imagePath);
		String maskPath = null;
        System.out.println(imageFile);
        System.out.println(File.separator);
        System.out.println(imageFile.getAbsolutePath());
        try {
            System.out.println(imageFile.getCanonicalPath());
        } catch(Exception ioe) {
            System.out.println(ioe);
        }
		//java.io.File maskFile = null;
        System.out.println("\nImage is located at:");
        //System.out.println(service.createImageVariation(request, imagePath).getData().get(0).getUrl());
        System.out.println(service.createImageEdit(request, imagePath, maskPath).getData().get(0).getUrl());
        //System.out.println(service.createImageEdit(request, imageFile, maskFile).getData().get(0).getUrl());
    }
}

C:\Users\andym\Downloads\openai-java-0.11.0\openai-java-0.11.0>.\gradlew.bat  example:run

> Task :example:run FAILED

Creating Image...
\images\dog_breakdancing_with_cat.png
\
C:\images\dog_breakdancing_with_cat.png
C:\images\dog_breakdancing_with_cat.png

Image is located at:
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.getBytes(java.nio.charset.Charset)" because "content" is null
        at okhttp3.RequestBody.create(RequestBody.java:109)
        at okhttp3.MultipartBody$Part.createFormData(MultipartBody.java:243)
        at okhttp3.MultipartBody$Builder.addFormDataPart(MultipartBody.java:322)
        at com.theokanning.openai.service.OpenAiService.createImageEdit(OpenAiService.java:171)
        at com.theokanning.openai.service.OpenAiService.createImageEdit(OpenAiService.java:162)
        at example.OpenAiApiExample.main(OpenAiApiExample.java:49)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':example:run'.
> Process 'command 'C:\Users\andym\Tools\processing-4.1.2\java\bin\java.exe'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
8 actionable tasks: 2 executed, 6 up-to-date

**Comment by ajavamind** [comment]
I found a solution to this issue with the following changes to the example I tested:

CreateImageEditRequest request = CreateImageEditRequest.builder()
.prompt("change colors to red")
.n(1)
.size("1024x1024")  // was missing
.responseFormat("url") // was missing
.build();

I also used GIMP to edit my image and make an alpha layer exporting as a 8bit RGBA type PNG file
I had to add a mask png to see any changes in my original image
And I had to change the timeout to 60 seconds in OpenAiService.java:    private static final Duration DEFAULT_TIMEOUT = Duration.ofSeconds(60);
