### ISSUE TITLE
"executorService must be set in order to shut down" error when attempting to close the service

### ISSUE THREAD

**Issue by Tomotopieces** [TheoKanning/openai-java#263]
I have been referencing the stream section of the openai-java example code and attempting to perform secondary wrapping on the project. I want to implement a simple stream-style chat. Below is my code:

*SimpleGPTClient.java*:

```java
package io.tomoto.openai;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.theokanning.openai.OpenAiApi;
import com.theokanning.openai.completion.chat.ChatCompletionRequest;
import com.theokanning.openai.completion.chat.ChatMessage;
import com.theokanning.openai.completion.chat.ChatMessageRole;
import com.theokanning.openai.service.OpenAiService;
import okhttp3.OkHttpClient;
import retrofit2.Retrofit;

import java.net.InetSocketAddress;
import java.net.Proxy;
import java.time.Duration;
import java.util.HashMap;
import java.util.List;

import static com.theokanning.openai.service.OpenAiService.*;

/**
 * @author Tomoto
 * @version 1.0
 * @since 2023/4/18 10:44
 */
public class SimpleGPTClient {
    private static final int CHOICES_AMOUNT = 1;

    private static final String MODEL = "gpt-3.5-turbo-0301";

    private static final double TEMPERATURE = 1.0;

    private static final int TIMEOUT_DURATION_OF_SECONDS = 30;

    private static final String API_KEY = "";

    private static final String HOST = "127.0.0.1";

    private static final Integer PORT = 7890;

    private OpenAiService openAiService;

    public SimpleGPTClient() {
        ObjectMapper mapper = defaultObjectMapper();
        OkHttpClient.Builder clientBuilder =
                defaultClient(API_KEY, Duration.ofSeconds(TIMEOUT_DURATION_OF_SECONDS)).newBuilder();
        clientBuilder.proxy(new Proxy(Proxy.Type.HTTP, new InetSocketAddress(HOST, PORT)));
        OkHttpClient client = clientBuilder.build();
        Retrofit retrofit = defaultRetrofit(client, mapper);
        OpenAiApi api = retrofit.create(OpenAiApi.class);
        this.openAiService = new OpenAiService(api);
    }

    public void streamChat(String prompt, String message) {
        ChatCompletionRequest request = ChatCompletionRequest.builder()
                .messages(formatMessages(prompt, message))
                .stream(true)
                .n(CHOICES_AMOUNT)
                .model(MODEL)
                .logitBias(new HashMap<>())
                .temperature(TEMPERATURE)
                .build();
        openAiService.streamChatCompletion(request)
                .doOnError(Throwable::printStackTrace)
                .blockingForEach(chunk -> {
                    String text = chunk.getChoices().get(0).getMessage().getContent();
                    if (text == null) {
                        return;
                    }
                    System.out.print(text);
                });
        openAiService.shutdownExecutor();
    }

    private static List<ChatMessage> formatMessages(String prompt, String message) {
        return List.of(
                new ChatMessage(ChatMessageRole.SYSTEM.value(), prompt),
                new ChatMessage(ChatMessageRole.USER.value(), message)
        );
    }
}

```

*Main.java*:

```java
package io.tomoto;

import io.tomoto.openai.SimpleGPTClient;

/**
 * @author Tomoto
 * @version 1.0
 * @since $DATE $TIME
 */
public class Main {
    public static void main(String[] args) {
        SimpleGPTClient client = new SimpleGPTClient();
        client.streamChat("You are a dog and will speak as such.", "Hey good boy how you dooooooooooooooooooooooing? *touch your head*");
    }
}
```

When the program runs, the response from GPT will be printed out one by one. However, after the response is complete, an error message will be generated:

```java
> Task :Main.main()
I'm doing great, thanks for asking! *wags tail happily*Exception in thread "main" java.lang.NullPointerException: executorService must be set in order to shut down
	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
	at com.theokanning.openai.service.OpenAiService.shutdownExecutor(OpenAiService.java:315)
	at io.tomoto.openai.SimpleGPTClient.streamChat(SimpleGPTClient.java:121)
	at io.tomoto.Main.main(Main.java:15)

> Task :Main.main() FAILED
```

The issue is with the `openAiService.shutdownExecutor()` code. If I remove this line of code, the program will end correctly, but it takes 60 seconds, which is not what I want.

**Comment by n3bul4** [comment]
Hey there,
if you want to use the shutdownExecutor method you must provide the ExecutorService from client.dispatcher().executorService() as an argument to the OpenAiService contructor.

```
/**
     * Creates a new OpenAiService that wraps OpenAiApi.
     * The ExecutoryService must be the one you get from the client you created the api with
     * otherwise shutdownExecutor() won't work. Use this if you need more customization.
     *
     * @param api OpenAiApi instance to use for all methods
     * @param executorService the ExecutorService from client.dispatcher().executorService()
     */
    public OpenAiService(final OpenAiApi api, final ExecutorService executorService) {
        this.api = api;
        this.executorService = executorService;
    }
```

Otherwise the ExecutorService will be null.

**Comment by Tomotopieces** [comment]
> Hey there, if you want to use the shutdownExecutor method you must provide the ExecutorService from client.dispatcher().executorService() as an argument to the OpenAiService contructor.
> 
> ```
> /**
>      * Creates a new OpenAiService that wraps OpenAiApi.
>      * The ExecutoryService must be the one you get from the client you created the api with
>      * otherwise shutdownExecutor() won't work. Use this if you need more customization.
>      *
>      * @param api OpenAiApi instance to use for all methods
>      * @param executorService the ExecutorService from client.dispatcher().executorService()
>      */
>     public OpenAiService(final OpenAiApi api, final ExecutorService executorService) {
>         this.api = api;
>         this.executorService = executorService;
>     }
> ```
> 
> Otherwise the ExecutorService will be null.

Thank you very much! After modifying the last line of code in the constructor to the following format, the error no longer occurs. 

```java
this.openAiService = new OpenAiService(api, client.dispatcher().executorService());
```

I think it is necessary to mention this point in the `example`.
