### ISSUE TITLE
request streaming demo

### ISSUE THREAD

**Issue by UltimateRedx** [TheoKanning/openai-java#266]
Hi, thanks for your work. 
I have encountered a question that application can't request proxy properly.
Can you provide a demo that use proxy and streaming method such as `streamChatCompletion`?

Here is my code, and okHttp always report broken pipe or connection reset.
```java 
        ObjectMapper mapper = OpenAiService.defaultObjectMapper();
        Proxy proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress("<my proxy server like a.aws.com>",  80));
        OkHttpClient client = OpenAiService.defaultClient("<my token>", Duration.ofSeconds(10L))
                .newBuilder()
                .proxy(proxy)
                .protocols(Collections.singletonList(Protocol.HTTP_1_1))
                .build();
        Retrofit retrofit = OpenAiService.defaultRetrofit(client, mapper);
        OpenAiApi api = retrofit.create(OpenAiApi.class);
        OpenAiService service = new OpenAiService(api, client.dispatcher().executorService());
        service.streamChatCompletion(ccr).subscribe(new Subscriber<>() {
              /* @Override  methods*/
        })
```

erroroutput:
```log
2023-04-23 10:27:07,191 [OkHttp https://api.openai.com/...] DEBUG TaskRunner - Q10013 scheduled after   0 µs: OkHttp ConnectionPool
2023-04-23 10:27:07,192 [OkHttp TaskRunner] DEBUG TaskRunner - Q10013 starting              : OkHttp ConnectionPool
2023-04-23 10:27:07,193 [OkHttp ConnectionPool] DEBUG TaskRunner - Q10013 run again after   1 s : OkHttp ConnectionPool
2023-04-23 10:27:07,194 [OkHttp https://api.openai.com/...] DEBUG TaskRunner - Q10013 canceled              : OkHttp ConnectionPool
2023-04-23 10:27:07,194 [OkHttp TaskRunner] DEBUG TaskRunner - Q10013 finished run in   2 ms: OkHttp ConnectionPool
2023-04-23 10:27:07,194 [OkHttp https://api.openai.com/...] ERROR 
java.net.SocketException: Broken pipe
	at sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:420) ~[?:?]
	at sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:440) ~[?:?]
	at sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:826) ~[?:?]
	at java.net.Socket$SocketOutputStream.write(Socket.java:1035) ~[?:?]
	at sun.security.ssl.SSLSocketOutputRecord.deliver(SSLSocketOutputRecord.java:345) ~[?:?]
	at sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:1298) ~[?:?]
	at okio.OutputStreamSink.write(JvmOkio.kt:57) ~[okio-jvm-3.0.0.jar:?]
	at okio.AsyncTimeout$sink$1.write(AsyncTimeout.kt:99) ~[okio-jvm-3.0.0.jar:?]
	at okio.RealBufferedSink.flush(RealBufferedSink.kt:267) ~[okio-jvm-3.0.0.jar:?]
	at okhttp3.internal.http1.Http1ExchangeCodec.finishRequest(Http1ExchangeCodec.kt:155) ~[okhttp-4.10.0.jar:?]
	at okhttp3.internal.connection.Exchange.finishRequest(Exchange.kt:91) ~[okhttp-4.10.0.jar:?]
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:76) ~[okhttp-4.10.0.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar:?]
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34) ~[okhttp-4.10.0.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar:?]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95) ~[okhttp-4.10.0.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar:?]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83) ~[okhttp-4.10.0.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar:?]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76) ~[okhttp-4.10.0.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar:?]
	at com.theokanning.openai.service.AuthenticationInterceptor.intercept(AuthenticationInterceptor.java:28) ~[service-0.12.0.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar:?]
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201) ~[okhttp-4.10.0.jar:?]
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517) ~[okhttp-4.10.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
2023-04-23 10:28:49,370 [OkHttp https://api.openai.com/...] DEBUG TaskRunner - Q10016 scheduled after   0 µs: OkHttp ConnectionPool
2023-04-23 10:28:49,372 [OkHttp TaskRunner] DEBUG TaskRunner - Q10016 starting              : OkHttp ConnectionPool
2023-04-23 10:28:49,372 [OkHttp ConnectionPool] DEBUG TaskRunner - Q10016 run again after   1 s : OkHttp ConnectionPool
2023-04-23 10:28:49,373 [OkHttp TaskRunner] DEBUG TaskRunner - Q10016 finished run in 992 µs: OkHttp ConnectionPool
2023-04-23 10:28:49,374 [OkHttp https://api.openai.com/...] DEBUG TaskRunner - Q10016 canceled              : OkHttp ConnectionPool
2023-04-23 10:28:49,374 [OkHttp https://api.openai.com/...] ERROR 
java.net.SocketException: Connection reset
	at sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323) ~[?:?]
	at sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350) ~[?:?]
	at sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803) ~[?:?]
	at java.net.Socket$SocketInputStream.read(Socket.java:966) ~[?:?]
	at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478) ~[?:?]
	at sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472) ~[?:?]
	at sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1455) ~[?:?]
	at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1059) ~[?:?]
	at okio.InputStreamSource.read(JvmOkio.kt:94) ~[okio-jvm-3.0.0.jar:?]
	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:125) ~[okio-jvm-3.0.0.jar:?]
	at okio.RealBufferedSource.indexOf(RealBufferedSource.kt:427) ~[okio-jvm-3.0.0.jar:?]
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:320) ~[okio-jvm-3.0.0.jar:?]
	at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29) ~[okhttp-4.10.0.jar:?]
	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178) ~[okhttp-4.10.0.jar:?]
	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106) ~[okhttp-4.10.0.jar:?]
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79) ~[okhttp-4.10.0.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar:?]
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34) ~[okhttp-4.10.0.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar:?]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95) ~[okhttp-4.10.0.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar:?]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83) ~[okhttp-4.10.0.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar:?]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76) ~[okhttp-4.10.0.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar:?]
	at com.theokanning.openai.service.AuthenticationInterceptor.intercept(AuthenticationInterceptor.java:28) ~[service-0.12.0.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar:?]
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201) ~[okhttp-4.10.0.jar:?]
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517) ~[okhttp-4.10.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

```

if i use proxy directly in postman, it works normally, here is the output:
```http
POST http://a.aws.com/v1/chat/completions
200
2.74 s
POST /v1/chat/completions HTTP/1.1
Content-Type: application/json
Authorization: Bearer <my token>
User-Agent: PostmanRuntime/7.32.2
Accept: */*
Postman-Token: 55dbcf13-553a-4af4-a3bd-1dd363c98a43
Host:a.aws.com
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 161
 
{
"model": "gpt-3.5-turbo",
"stream": true,
"messages":[
{
"role": "user",
"content": "who are you"
}
]
}
 
HTTP/1.1 200 OK
Server: nginx/1.24.0
Date: Sun, 23 Apr 2023 02:18:33 GMT
Content-Type: text/event-stream
Transfer-Encoding: chunked
Connection: keep-alive
access-control-allow-origin: *
Cache-Control: no-cache, must-revalidate
openai-model: gpt-3.5-turbo-0301
openai-organization: <hidden>
openai-processing-ms: 375
openai-version: 2020-10-01
strict-transport-security: max-age=15724800; includeSubDomains
x-ratelimit-limit-requests: 3500
x-ratelimit-remaining-requests: 3499
x-ratelimit-reset-requests: 17ms
x-request-id: 5e9e0bf6b8bc8a7f3d7274d4f23db51d
CF-Cache-Status: DYNAMIC
CF-RAY: 7bc29dd45c742a78-ORD
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
 
data: {"id":"chatcmpl-78Jb7yXXW7LORjoUqz2A6c9YwSOYk","object":"chat.completion.chunk","created":1682216313,"model":"gpt-3.5-turbo-0301","choices":[{"delta":{"role":"assistant"},"index":0,"finish_reason":null}]}
data: {"id":"chatcmpl-78Jb7yXXW7LORjoUqz2A6c9YwSOYk","object":"chat.completion.chunk","created":1682216313,"model":"gpt-3.5-turbo-0301","choices":[{"delta":{"content":"I"},"index":0,"finish_reason":null}]}
data: {"id":"chatcmpl-78Jb7yXXW7LORjoUqz2A6c9YwSOYk","object":"chat.completion.chunk","created":1682216313,"model":"gpt-3.5-turbo-0301","choices":[{"delta":{"content":" am"},"index":0,"finish_reason":null}]}
data: {"id":"chatcmpl-78Jb7yXXW7LORjoUqz2A6c9YwSOYk","object":"chat.completion.chunk","created":1682216313,"model":"gpt-3.5-turbo-0301","choices":[{"delta":{"content":" an"},"index":0,"finish_reason":null}]}
data: {"id":"chatcmpl-78Jb7yXXW7LORjoUqz2A6c9YwSOYk","object":"chat.completion.chunk","created":1682216313,"model":"gpt-3.5-turbo-0301","choices":[{"delta":{"content":" AI"},"index":0,"finish_reason":null}]}
data: {"id":"chatcmpl-78Jb7yXXW7LORjoUqz2A6c9YwSOYk","object":"chat.completion.chunk","created":1682216313,"model":"gpt-3.5-turbo-0301","choices":[{"delta":{"content":" language"},"index":0,"finish_reason":null}]}
data: {"id":"chatcmpl-78Jb7yXXW7LORjoUqz2A6c9YwSOYk","object":"chat.completion.chunk","created":1682216313,"model":"gpt-3.5-turbo-0301","choices":[{"delta":{"content":" model"},"index":0,"finish_reason":null}]}
data: {"id":"chatcmpl-78Jb7yXXW7LORjoUqz2A6c9YwSOYk","object":"chat.completion.chunk","created":1682216313,"model":"gpt-3.5-turbo-0301","choices":[{"delta":{"content":" created"},"index":0,"finish_reason":null}]}
data: {"id":"chatcmpl-78Jb7yXXW7LORjoUqz2A6c9YwSOYk","object":"chat.completion.chunk","created":1682216313,"model":"gpt-3.5-turbo-0301","choices":[{"delta":{"content":" by"},"index":0,"finish_reason":null}]}
data: {"id":"chatcmpl-78Jb7yXXW7LORjoUqz2A6c9YwSOYk","object":"chat.completion.chunk","created":1682216313,"model":"gpt-3.5-turbo-0301","choices":[{"delta":{"content":" Open"},"index":0,"finish_reason":null}]}
data: {"id":"chatcmpl-78Jb7yXXW7LORjoUqz2A6c9YwSOYk","object":"chat.completion.chunk","created":1682216313,"model":"gpt-3.5-turbo-0301","choices":[{"delta":{"content":"AI"},"index":0,"finish_reason":null}]}
data: {"id":"chatcmpl-78Jb7yXXW7LORjoUqz2A6c9YwSOYk","object":"chat.completion.chunk","created":1682216313,"model":"gpt-3.5-turbo-0301","choices":[{"delta":{"content":"."},"index":0,"finish_reason":null}]}
data: {"id":"chatcmpl-78Jb7yXXW7LORjoUqz2A6c9YwSOYk","object":"chat.completion.chunk","created":1682216313,"model":"gpt-3.5-turbo-0301","choices":[{"delta":{"content":" I"},"index":0,"finish_reason":null}]}
data: {"id":"chatcmpl-78Jb7yXXW7LORjoUqz2A6c9YwSOYk","object":"chat.completion.chunk","created":1682216313,"model":"gpt-3.5-turbo-0301","choices":[{"delta":{"content":" am"},"index":0,"finish_reason":null}]}
data: {"id":"chatcmpl-78Jb7yXXW7LORjoUqz2A6c9YwSOYk","object":"chat.completion.chunk","created":1682216313,"model":"gpt-3.5-turbo-0301","choices":[{"delta":{"content":" designed"},"index":0,"finish_reason":null}]}
data: {"id":"chatcmpl-78Jb7yXXW7LORjoUqz2A6c9YwSOYk","object":"chat.completion.chunk","created":1682216313,"model":"gpt-3.5-turbo-0301","choices":[{"delta":{"content":" to"},"index":0,"finish_reason":null}]}
data: {"id":"chatcmpl-78Jb7yXXW7LORjoUqz2A6c9YwSOYk","object":"chat.completion.chunk","created":1682216313,"model":"gpt-3.5-turbo-0301","choices":[{"delta":{"content":" assist"},"index":0,"finish_reason":null}]}
data: {"id":"chatcmpl-78Jb7yXXW7LORjoUqz2A6c9YwSOYk","object":"chat.completion.chunk","created":1682216313,"model":"gpt-3.5-turbo-0301","choices":[{"delta":{"content":" in"},"index":0,"finish_reason":null}]}
data: {"id":"chatcmpl-78Jb7yXXW7LORjoUqz2A6c9YwSOYk","object":"chat.completion.chunk","created":1682216313,"model":"gpt-3.5-turbo-0301","choices":[{"delta":{"content":" generating"},"index":0,"finish_reason":null}]}
data: {"id":"chatcmpl-78Jb7yXXW7LORjoUqz2A6c9YwSOYk","object":"chat.completion.chunk","created":1682216313,"model":"gpt-3.5-turbo-0301","choices":[{"delta":{"content":" human"},"index":0,"finish_reason":null}]}
data: {"id":"chatcmpl-78Jb7yXXW7LORjoUqz2A6c9YwSOYk","object":"chat.completion.chunk","created":1682216313,"model":"gpt-3.5-turbo-0301","choices":[{"delta":{"content":"-like"},"index":0,"finish_reason":null}]}
data: {"id":"chatcmpl-78Jb7yXXW7LORjoUqz2A6c9YwSOYk","object":"chat.completion.chunk","created":1682216313,"model":"gpt-3.5-turbo-0301","choices":[{"delta":{"content":" responses"},"index":0,"finish_reason":null}]}
data: {"id":"chatcmpl-78Jb7yXXW7LORjoUqz2A6c9YwSOYk","object":"chat.completion.chunk","created":1682216313,"model":"gpt-3.5-turbo-0301","choices":[{"delta":{"content":" to"},"index":0,"finish_reason":null}]}
data: {"id":"chatcmpl-78Jb7yXXW7LORjoUqz2A6c9YwSOYk","object":"chat.completion.chunk","created":1682216313,"model":"gpt-3.5-turbo-0301","choices":[{"delta":{"content":" text"},"index":0,"finish_reason":null}]}
data: {"id":"chatcmpl-78Jb7yXXW7LORjoUqz2A6c9YwSOYk","object":"chat.completion.chunk","created":1682216313,"model":"gpt-3.5-turbo-0301","choices":[{"delta":{"content":"-based"},"index":0,"finish_reason":null}]}
data: {"id":"chatcmpl-78Jb7yXXW7LORjoUqz2A6c9YwSOYk","object":"chat.completion.chunk","created":1682216313,"model":"gpt-3.5-turbo-0301","choices":[{"delta":{"content":" communication"},"index":0,"finish_reason":null}]}
data: {"id":"chatcmpl-78Jb7yXXW7LORjoUqz2A6c9YwSOYk","object":"chat.completion.chunk","created":1682216313,"model":"gpt-3.5-turbo-0301","choices":[{"delta":{"content":"."},"index":0,"finish_reason":null}]}
data: {"id":"chatcmpl-78Jb7yXXW7LORjoUqz2A6c9YwSOYk","object":"chat.completion.chunk","created":1682216313,"model":"gpt-3.5-turbo-0301","choices":[{"delta":{},"index":0,"finish_reason":"stop"}]}
data: [DONE]

```

**Comment by UltimateRedx** [comment]
sorry. connection / read time set is too short..

**Comment by Tomotopieces** [comment]
鉴于你的仓库里有中文commit，就当是国人了。不知道你的问题解决了没有，希望能帮到你。

这是我提过的一个Issue，里面有我进行二次封装的代码：

#263 

我之后又进行了一些修改，大致是这样的：

```java
public SimpleGPTClient() {
    ObjectMapper mapper = defaultObjectMapper();
    OkHttpClient client = defaultClient(API_KEY, Duration.ofSeconds(TIMEOUT_SECONDS))
            .newBuilder()
            .proxy(new Proxy(Proxy.Type.HTTP, new InetSocketAddress(HOST, PORT)))
            .build();
    Retrofit retrofit = defaultRetrofit(client, mapper);
    OpenAiApi api = retrofit.create(OpenAiApi.class);
    this.openAiService = new OpenAiService(api, client.dispatcher().executorService());
}

public void streamChat(String prompt, String message) {
    ChatCompletionRequest request = ChatCompletionRequest.builder()
            .messages(formatMessages(prompt, message))
            .stream(true)
            .n(CHOICES_AMOUNT)
            .model(MODEL)
            .logitBias(new HashMap<>())
            .temperature(TEMPERATURE)
            .build();
    openAiService.streamChatCompletion(request).subscribe(chunk -> {
        String text = chunk.getChoices().get(0).getMessage().getContent();
        if (text == null) {
            return;
        }
        System.out.print(text);
    }, Throwable::printStackTrace, openAiService::shutdownExecutor);
}
```

与你的代码的差别在于这几处：

1. 你的`OkHttpClient`添加了协议：`.protocols(Collections.singletonList(Protocol.HTTP_1_1))`；
   - 在我的代码中添加这段后进行了测试，没有问题。应该不是这里的原因。
2. 你的`streamChatCompletion`的参数没有写明；
3. 你的`subscribe`参数没有写明。

你可以基于后两点进行排查。如果还是不行，就需要排查环境原因了。

我的环境：

- JDK Oracle OpenJDK 17.0.1
- dependencies:
  - implementation 'com.theokanning.openai-gpt3-java:service:0.12.0'
  - implementation 'com.fasterxml.jackson.core:jackson-databind:2.14.2'

---

Considering there are Chinese commits in your repository, I assume you are a Chinese. I’m not sure if your issue has been resolved, but I hope I can help you.

This is an issue I raised, and it contains my second-level packaged code:

#263

Later, I made some modifications, which look like this:

```java
public SimpleGPTClient() {
    ObjectMapper mapper = defaultObjectMapper();
    OkHttpClient client = defaultClient(API_KEY, Duration.ofSeconds(TIMEOUT_SECONDS))
            .newBuilder()
            .proxy(new Proxy(Proxy.Type.HTTP, new InetSocketAddress(HOST, PORT)))
            .build();
    Retrofit retrofit = defaultRetrofit(client, mapper);
    OpenAiApi api = retrofit.create(OpenAiApi.class);
    this.openAiService = new OpenAiService(api, client.dispatcher().executorService());
}

public void streamChat(String prompt, String message) {
    ChatCompletionRequest request = ChatCompletionRequest.builder()
            .messages(formatMessages(prompt, message))
            .stream(true)
            .n(CHOICES_AMOUNT)
            .model(MODEL)
            .logitBias(new HashMap<>())
            .temperature(TEMPERATURE)
            .build();
    openAiService.streamChatCompletion(request).subscribe(chunk -> {
        String text = chunk.getChoices().get(0).getMessage().getContent();
        if (text == null) {
            return;
        }
        System.out.print(text);
    }, Throwable::printStackTrace, openAiService::shutdownExecutor);
}
```

The differences between my code and yours are:

1. Your OkHttpClient added a protocol: .protocols(Collections.singletonList(Protocol.HTTP_1_1));
- After adding this in my code and running some tests, there was no problem. It is not likely the reason here.
2. Your parameter for streamChatCompletion was not specified;
3. Your parameter for subscribe was not specified.

You can troubleshoot based on the last two points. If it still does not work, you need to investigate environmental reasons.

My environment:

- JDK Oracle OpenJDK 17.0.1
- dependencies:
  - implementation 'com.theokanning.openai-gpt3-java:service:0.12.0'
  - implementation 'com.fasterxml.jackson.core:jackson-databind:2.14.2'

**Comment by UltimateRedx** [comment]
> 鉴于你的仓库里有中文commit，就当是国人了。不知道你的问题解决了没有，希望能帮到你。
> 
> 这是我提过的一个Issue，里面有我进行二次封装的代码：
> 
> #263
> 
> 我之后又进行了一些修改，大致是这样的：
> 
> ```java
> public SimpleGPTClient() {
>     ObjectMapper mapper = defaultObjectMapper();
>     OkHttpClient client = defaultClient(API_KEY, Duration.ofSeconds(TIMEOUT_SECONDS))
>             .newBuilder()
>             .proxy(new Proxy(Proxy.Type.HTTP, new InetSocketAddress(HOST, PORT)))
>             .build();
>     Retrofit retrofit = defaultRetrofit(client, mapper);
>     OpenAiApi api = retrofit.create(OpenAiApi.class);
>     this.openAiService = new OpenAiService(api, client.dispatcher().executorService());
> }
> 
> public void streamChat(String prompt, String message) {
>     ChatCompletionRequest request = ChatCompletionRequest.builder()
>             .messages(formatMessages(prompt, message))
>             .stream(true)
>             .n(CHOICES_AMOUNT)
>             .model(MODEL)
>             .logitBias(new HashMap<>())
>             .temperature(TEMPERATURE)
>             .build();
>     openAiService.streamChatCompletion(request).subscribe(chunk -> {
>         String text = chunk.getChoices().get(0).getMessage().getContent();
>         if (text == null) {
>             return;
>         }
>         System.out.print(text);
>     }, Throwable::printStackTrace, openAiService::shutdownExecutor);
> }
> ```
> 
> 与你的代码的差别在于这几处：
> 
> 1. 你的`OkHttpClient`添加了协议：`.protocols(Collections.singletonList(Protocol.HTTP_1_1))`；
>    
>    * 在我的代码中添加这段后进行了测试，没有问题。应该不是这里的原因。
> 2. 你的`streamChatCompletion`的参数没有写明；
> 3. 你的`subscribe`参数没有写明。
> 
> 你可以基于后两点进行排查。如果还是不行，就需要排查环境原因了。
> 
> 我的环境：
> 
> * JDK Oracle OpenJDK 17.0.1
> * dependencies:
>   
>   * implementation 'com.theokanning.openai-gpt3-java:service:0.12.0'
>   * implementation 'com.fasterxml.jackson.core:jackson-databind:2.14.2'
> 
> Considering there are Chinese commits in your repository, I assume you are a Chinese. I’m not sure if your issue has been resolved, but I hope I can help you.
> 
> This is an issue I raised, and it contains my second-level packaged code:
> 
> #263
> 
> Later, I made some modifications, which look like this:
> 
> ```java
> public SimpleGPTClient() {
>     ObjectMapper mapper = defaultObjectMapper();
>     OkHttpClient client = defaultClient(API_KEY, Duration.ofSeconds(TIMEOUT_SECONDS))
>             .newBuilder()
>             .proxy(new Proxy(Proxy.Type.HTTP, new InetSocketAddress(HOST, PORT)))
>             .build();
>     Retrofit retrofit = defaultRetrofit(client, mapper);
>     OpenAiApi api = retrofit.create(OpenAiApi.class);
>     this.openAiService = new OpenAiService(api, client.dispatcher().executorService());
> }
> 
> public void streamChat(String prompt, String message) {
>     ChatCompletionRequest request = ChatCompletionRequest.builder()
>             .messages(formatMessages(prompt, message))
>             .stream(true)
>             .n(CHOICES_AMOUNT)
>             .model(MODEL)
>             .logitBias(new HashMap<>())
>             .temperature(TEMPERATURE)
>             .build();
>     openAiService.streamChatCompletion(request).subscribe(chunk -> {
>         String text = chunk.getChoices().get(0).getMessage().getContent();
>         if (text == null) {
>             return;
>         }
>         System.out.print(text);
>     }, Throwable::printStackTrace, openAiService::shutdownExecutor);
> }
> ```
> 
> The differences between my code and yours are:
> 
> 1. Your OkHttpClient added a protocol: .protocols(Collections.singletonList(Protocol.HTTP_1_1));
> 
> * After adding this in my code and running some tests, there was no problem. It is not likely the reason here.
> 
> 2. Your parameter for streamChatCompletion was not specified;
> 3. Your parameter for subscribe was not specified.
> 
> You can troubleshoot based on the last two points. If it still does not work, you need to investigate environmental reasons.
> 
> My environment:
> 
> * JDK Oracle OpenJDK 17.0.1
> * dependencies:
>   
>   * implementation 'com.theokanning.openai-gpt3-java:service:0.12.0'
>   * implementation 'com.fasterxml.jackson.core:jackson-databind:2.14.2'

@Tomotopieces  Thanks for the advice.

I do not think the real problem of my question is relevant to the code I did't show.

I think the problem is that  okHttp will try to `CONNECT` proxy server first. which the http `CONNECT` method is not used often.
 
 And the  Nignx i used for forwarding proxy,  don't support `CONNECT` officially .
 
 I tried to add a module [ngx_http_proxy_connect_module](https://github.com/chobits/ngx_http_proxy_connect_module). The examle code from the repo runs like a charm. But my java code does't work like that.
 Maybe the module is't what I am looking for.
 
<p>So, streaming HTTP `POST `method is fine, HTTP `CONNECT` method, not so much.</p>
<p>if the author see this, can you try to use HTTP `Post` method instead of `CONNECT`.</p>
And i don't see a method that you can push data to openai server through tunnel.  so why bother try to create a one.

**Comment by wangran99** [comment]
`Disposable subscribe = openAiService.streamChatCompletion(chatCompletionRequest)
                .doOnSubscribe(e -> startHandle(userIdentity))
                .subscribe(chat -> convertAndSendResponse(chat),
                        throwable -> errorHandle(throwable),
                        () -> completeHandle());`
