### ISSUE TITLE
executorService must be set in order to shut down

### ISSUE THREAD

**Issue by 1459347320** [TheoKanning/openai-java#277]
ChatCompletionRequest chatCompletionRequest = ChatCompletionRequest
                .builder()
                .model("gpt-3.5-turbo")
                .messages(messages)
                .n(1)
                .maxTokens(50)
                .logitBias(new HashMap<>())
                .build();
        service.streamChatCompletion(chatCompletionRequest)
                .doOnError(Throwable::printStackTrace)
                .blockingForEach(System.out::println);
        service.shutdownExecutor();

**Comment by 1459347320** [comment]
java.lang.NullPointerException: executorService must be set in order to shut down
	at java.util.Objects.requireNonNull(Objects.java:228)
	at com.theokanning.openai.service.OpenAiService.shutdownExecutor(OpenAiService.java:315)
	at com.ly.user.controller.TestController.main(TestController.java:174)

**Comment by 1459347320** [comment]
OpenAiService service = new OpenAiService(api,client.dispatcher().executorService());
在创建service的时候需要注入client.dispatcher().executorService()，这是在作者的示例中所没有的
