### ISSUE TITLE
Billing usage returns retrofit2.adapter.rxjava2.HttpException: HTTP 403

### ISSUE THREAD

**Issue by ronenkluska** [TheoKanning/openai-java#349]
I'm using the OpenAI Service and regular endpoints like chat completion works properly. When I try to use the new `subscription` and `billingUsage` I keep getting `retrofit2.adapter.rxjava2.HttpException: HTTP 403` even though I'm using the same OpenAI service object.

This is how I initialize the service:
```java
String apiKey = System.getenv(API_KEY);
var clientBuilder = defaultClient(apiKey, timeout)
    .newBuilder();
Retrofit retrofit = defaultRetrofit(clientBuilder.build(), defaultObjectMapper());
OpenAiApi api = retrofit.create(OpenAiApi.class);
OpenAiService openAiService = new OpenAiService(api);
```

This is how I'm calling the different endpoints:
```java
// Billing usage from the last day
LocalDate now = LocalDate.now();
BillingUsage billing = openAiService.billingUsage(now.minusDays(1),now);

// Subscription info
Subscription subscription = openAiService.subscription();
```

The errors I get:
```
! retrofit2.adapter.rxjava2.HttpException: HTTP 403
! at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:57)
! at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:38)
! at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:48)
! at io.reactivex.Observable.subscribe(Observable.java:10151)
! at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35)
! at io.reactivex.Observable.subscribe(Observable.java:10151)
! at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
! at io.reactivex.Single.subscribe(Single.java:2517)
! at io.reactivex.Single.blockingGet(Single.java:2001)
! at com.theokanning.openai.service.OpenAiService.billingUsage(OpenAiService.java:467)
! at com.booking.llm.openai.client.OpenAIClient.getBilling(OpenAIClient.java:150)

! retrofit2.adapter.rxjava2.HttpException: HTTP 403
! at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:57)
! at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:38)
! at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:48)
! at io.reactivex.Observable.subscribe(Observable.java:10151)
! at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35)
! at io.reactivex.Observable.subscribe(Observable.java:10151)
! at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
! at io.reactivex.Single.subscribe(Single.java:2517)
! at io.reactivex.Single.blockingGet(Single.java:2001)
! at com.theokanning.openai.service.OpenAiService.subscription(OpenAiService.java:454)
```

Any idea what I'm doing wrong here?

**Comment by DevEmperor** [comment]
Same issue :/

**Comment by DevEmperor** [comment]
Using the curl command, I get the following issue:

`curl https://api.openai.com/v1/dashboard/billing/usage -H "Authorization: Bearer sk-Jqqm..."`

"Your request to GET /v1/dashboard/billing/usage must be made with a session key (that is, it can only be made from the browser). You made it with the following key type: secret."

**Comment by kingxjs** [comment]
This is possible, but using OpenAiService is not feasible
`curl https://api.openai.com/v1/dashboard/billing/usage 
-H "Authorization: Bearer sk-Sv..." 
-H "Host: api.openai.com" 
-H "Connection: Keep-Alive" 
-H "Accept-Encoding: gzip" 
-H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/536.36 Edg/113.0.1774.42" --output arthas`
