### ISSUE TITLE
createCompletion fails

### ISSUE THREAD

**Issue by ChanHaoHao** [TheoKanning/openai-java#356]
I am trying to use OpenAI in my Android project, but I fail to use "text-davinci-003", I have tried to use the example code, but it still fails

The following is my code:
```
OpenAiService service = new OpenAiService(ChatGPTAPIkey, Duration.ofSeconds(30));

CompletionRequest completionRequest = CompletionRequest.builder()
                        .model("text-davinci-003").prompt("Tell me a joke").echo(true).user("testing").n(1).build();
Log.d(TAG, service.createCompletion(completionRequest).getChoices().get(0).getText());
```
This is the error log:
```
android.os.NetworkOnMainThreadException
       at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1513)
       at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:117)
       at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:105)
       at java.net.InetAddress.getAllByName(InetAddress.java:1154)
       at okhttp3.Dns$Companion$DnsSystem.lookup(Dns.kt:49)
       at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.kt:164)
       at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.kt:129)
       at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:71)
       at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:205)
       at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
       at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
       at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at com.theokanning.openai.service.AuthenticationInterceptor.intercept(AuthenticationInterceptor.java:28)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
       at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
       at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
       at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:46)
       at io.reactivex.Observable.subscribe(Observable.java:10842)
       at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35)
       at io.reactivex.Observable.subscribe(Observable.java:10842)
       at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
       at io.reactivex.Single.subscribe(Single.java:2703)
       at io.reactivex.Single.blockingGet(Single.java:2156)
       at com.theokanning.openai.service.OpenAiService.execute(OpenAiService.java:321)
       at com.theokanning.openai.service.OpenAiService.createCompletion(OpenAiService.java:125)
```

**Comment by n3bul4** [comment]
@ChanHaoHao NetworkOnMainThreadException is thrown when an application attempts to perform a networking operation on its main thread. This exception is thrown since Honeycomb SDK because networking tasks can take a long time and could block the main application thread. You should run your code in a seperate thread.
