### ISSUE TITLE
Suggest changing nEpochs in Hyperparameters to string type

### ISSUE THREAD

**Issue by FlorriaWang** [TheoKanning/openai-java#372]
I don't want to set the nEpochs parameter in Hyperparameters, which returns type conversion errors when using the default value of auto

The exceptions are as follows：

java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.lang.Integer` from String "auto": not a valid Integer value
 at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 418] (through reference chain: com.theokanning.openai.fine_tuning.FineTuningJob["hyperparameters"]->com.theokanning.openai.fine_tuning.Hyperparameters["n_epochs"])

	at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
	at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:93)
	at io.reactivex.Single.blockingGet(Single.java:2835)
	at com.theokanning.openai.service.OpenAiService.execute(OpenAiService.java:349)
	at com.theokanning.openai.service.OpenAiService.createFineTuningJob(OpenAiService.java:177)

**Comment by wellitried** [comment]
+1
For me this bug renders the whole (otherwise nice) library useless
