### ISSUE TITLE
setting http timeout for okhttpclient used in the library

### ISSUE THREAD

**Issue by hanif-meras** [TheoKanning/openai-java#434]
Hi
When my connection is not so good i get this error
basically i solve this by setting okhttpclient a bigger timeout in other similar places by using this code:
OkHttpClient client = new OkHttpClient.Builder().readTimeout(120, TimeUnit.SECONDS).build();

is there a way (configuration) to change this parameter for this library?

java.lang.RuntimeException: java.net.SocketTimeoutException: timeout
        at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:45) ~[xxxxx.jar:?]
        at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:90) ~[xxxxx.jar:?]
        at io.reactivex.Maybe.blockingGet(Maybe.java:1931) ~[xxxxx.jar:?]
        at xxxxx(xxxxx.java:193) [xxxxx.jar:?]
        at xxxxx(xxxxx.java:23) [xxxxx.jar:?]
        at java.lang.Thread.run(Thread.java:1589) [?:?]
Caused by: java.net.SocketTimeoutException: timeout
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:678) ~[xxxxx.jar:?]
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:686) ~[xxxxx.jar:?]
        at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.java:409) ~[xxxxx.jar:?]
        at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.java:286) ~[xxxxx.jar:?]
        at okio.RealBufferedSource.read(RealBufferedSource.java:51) ~[xxxxx.jar:?]
        at okio.ForwardingSource.read(ForwardingSource.java:35) ~[xxxxx.jar:?]
        at retrofit2.OkHttpCall$ExceptionCatchingResponseBody$1.read(OkHttpCall.java:314) ~[xxxxx.jar:?]
        at okio.RealBufferedSource$1.read(RealBufferedSource.java:447) ~[xxxxx.jar:?]
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:333) ~[?:?]
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:376) ~[?:?]
        at sun.nio.cs.StreamDecoder.lockedRead(StreamDecoder.java:219) ~[?:?]
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:173) ~[?:?]
        at java.io.InputStreamReader.read(InputStreamReader.java:189) ~[?:?]
        at java.io.BufferedReader.fill(BufferedReader.java:161) ~[?:?]
        at java.io.BufferedReader.implReadLine(BufferedReader.java:371) ~[?:?]
        at java.io.BufferedReader.readLine(BufferedReader.java:348) ~[?:?]
        at java.io.BufferedReader.readLine(BufferedReader.java:437) ~[?:?]
        at com.theokanning.openai.service.ResponseBodyCallback.onResponse(ResponseBodyCallback.java:62) ~[xxxxx.jar:?]
        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:161) ~[xxxxx.jar:?]
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174) ~[xxxxx.jar:?]
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) ~[xxxxx.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        ... 1 more

**Comment by peterjkirby** [comment]
@hanif-meras 

Here is how I'm configuring timeouts, hopefully this helps:

```
    public OpenAiService openAiService(String apiKey, Duration timeout) {
        final ObjectMapper mapper = OpenAiService.defaultObjectMapper();
        final OkHttpClient client = OpenAiService.defaultClient(apiKey, timeout);
        final Retrofit retrofit = OpenAiService.defaultRetrofit(client, mapper);
        final OpenAiApi api = retrofit.create(OpenAiApi.class);
        return new OpenAiService(api);
    }
```

**Comment by hanif-meras** [comment]
Thanks Peter
That helped
Is there any complete documentation for this library?
