### ISSUE TITLE
Embeddings Endpoint Error

### ISSUE THREAD

**Issue by eugenedw** [TheoKanning/openai-java#96]
I'm trying to process an embedding, but receive a 404 error. My suspicion is that the endpoint takes a string, but the current implementation in this library sends an array of tokens.

```
SimpleTokenizer tokenizer = new SimpleTokenizer();
List<String> tokens = tokenizer.tokenize(textToEmbed);
HyphenNormalizer hyphenNormalizer = new HyphenNormalizer();
tokens = hyphenNormalizer.preprocess(tokens);
UnicodeNormalizer unicodeNormalizer = new UnicodeNormalizer();
tokens = unicodeNormalizer.preprocess(tokens);

EmbeddingRequest embeddingRequest = EmbeddingRequest.builder().input(tokens).model(model.toString()).build();
EmbeddingResult embedding = openAiService.createEmbeddings(embeddingRequest);
```

Here's the outcome:

```
retrofit2.adapter.rxjava2.HttpException: HTTP 404 
	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:57) ~[adapter-rxjava2-2.9.0.jar:na]
	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:38) ~[adapter-rxjava2-2.9.0.jar:na]
	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:48) ~[adapter-rxjava2-2.9.0.jar:na]
	at io.reactivex.Observable.subscribe(Observable.java:10151) ~[rxjava-2.0.0.jar:2.0.0]
	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35) ~[adapter-rxjava2-2.9.0.jar:na]
	at io.reactivex.Observable.subscribe(Observable.java:10151) ~[rxjava-2.0.0.jar:2.0.0]
	at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35) ~[rxjava-2.0.0.jar:2.0.0]
	at io.reactivex.Single.subscribe(Single.java:2517) ~[rxjava-2.0.0.jar:2.0.0]
	at io.reactivex.Single.blockingGet(Single.java:2001) ~[rxjava-2.0.0.jar:2.0.0]
	at com.theokanning.openai.OpenAiService.createEmbeddings(OpenAiService.java:140) ~[client-0.9.0.jar:na]
```

Here's what's in the relevant lines of code:

OpenAIService.java:140
```
    public EmbeddingResult createEmbeddings(EmbeddingRequest request) {
        return (EmbeddingResult)this.api.createEmbeddings(request).blockingGet();
    }
```

**Comment by eugenedw** [comment]
Resolved after more testing. Turns out I was sending the wrong model name to the endpoint.
